{% set name = "calysto_bash" %}
{% set version = "0.2.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4e3869f7c86a534085deb88bc6af6f41d1b5e105638f8958398a62029996510f

build:
  number: 4
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
    - {{ PYTHON }} -m calysto_bash install --sys-prefix

requirements:
  host:
    - pip
    - python
    - ipykernel
    - metakernel
    - setuptools
  run:
    - python >=3.10
    - ipykernel
    - ipyparallel
    - jupyter_client
    - metakernel

test:
  imports:
    - calysto_bash
  commands:
    - jupyter kernelspec list | grep calysto_bash
    - jupyter run --kernel=calysto_bash command.sh
  files:
    - command.sh

about:
  home: https://github.com/Calysto/calysto_bash
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "A Jupyter kernel for bash"
  doc_url: https://github.com/Calysto/calysto_bash
  dev_url: https://github.com/Calysto/calysto_bash

extra:
  recipe-maintainers:
    - blink1073
    - BoPeng
