travis:
  secure:
    BINSTAR_TOKEN: jXF0rgyoVSQoUdseClyeVIAyRw4sYrZFsW44l0wbnZXUMCSN3dVbyAS91O2ZfSTDe+/U4D9BqdbM/sCy6rvcbyLdSa9XS1jmTKmw/e4gEAMO/2OLbX8tgQxomBZoz5NMFRjmnB1WgG5ZKMuEqHozaaQayfP27jNwleRIPwWAzNoP7W+AyTBPpeMkgQXRGCY9MxlAqvkUZwoqWiUMVxe/6UgssOs7ydXp/HC/Be62pZLghbtpIqauhR1Rob7TtPPfCexynIOsSYHqE1mELw7s3O1w/729zSyF110abJRjQlUEvpxqASnRyCabrcMReS8Y4LOofTjaaYZ6DeVAxgiX4u9G888krMIIlsnHXRRkxCLt/qr45WgvLSyjXvWIQBDWyWc2u3brllWgchFSM/fWrBUNfqALLhyE8IRsyiO1YqZDr1X2n0QKrNfCNbaAEX93H9FgqibqAHU4MBJQ1kvBxRFadaCFNUpSWDXJ9Naq9gNHGnHn26GawIpXal0uGSPkN2jep1CDci/boAyP8g76+fKxKwqeL8rRHC7cZlHLQBGh4wOFoKbQr6Rog1F7PxbDs/4oX/68uDbUT9hakV6osU38ECUzRpakBhr0eFLK8ORS2W3XnjLTKL/LB7Lm32yFrsdix78GHtKkBPfywIpuY5Sfpw9rpnnpUDpwErbjPl0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
