travis:
  secure:
    BINSTAR_TOKEN: pbrVnKtGZfZw9rb/D+xS/QHggPtN4jNw6vZoxnudOAiy5yDwnc96A9jCLArvfwW13i+bXHIDM355jiHzXscLdKNaBiVBtjAjM65e3oeGGwv/x+sf3KSuc1BPcoUyhRg+WRQtVDjOeO3DwwULBVX2eF1P63EMi7jF61gD4V+sSmBDCSHIY+Icy9MXviXnNTaJETDniKYppp6kIrQmkYlDYWp6+DnYtdFu6Hes621ICPdnDu5k4em+9UBjiR19pi3TWEG4/BnbX6StxWS2MwVJnNKfTAbEBJSYJFHI9vvp2CXpuX/YdRm1XQhNCZNQ2heE4Es+ywtew2J4wzntcs0uYV66uFaNw9yVC57HmzKqbqIKv+Qqj7b0TYGqDIb0Ww79qLChe4wwSy4uT/NlDW8jhDgPHzn37nemvJARxtg7fc1Xa3DWoEvQvrjsRKxAupZBPxsFE/AEUfxBTJDvW9XVZUY6uU73Ro0KRqwbK+JBQ/ad7lFLC75AbdpWgYfPvctIZn4LAMC65gVJ/IBYuEPu1ROBfiCojezlR9fPn0eMFe2DWyFwNWK6Pm2GiR2l7TqqvLAlNNRDZpx3dCcjKX387nuOJIX2CsAokdXB/rSCY30jjDF5npF8bvlNW7KPsibKoAaKd567C/UFxi1LeTWkKJz2NArkkED/3es3cq5MCUI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure